### ISSUE TITLE
Sorting is buggy

### ISSUE THREAD

**Issue by bark** [cthit/EatIT#11]
If Horv order caprizosa Bark order kebab and Tuna order kebab.
The indexes is incorrect so next person clicking on kebab get caprizosa and vise verse

**Comment by bark** [comment]
Chromium Version 47.0.2526.73 Ubuntu 15.10 (64-bit)

**Comment by lindskogen** [comment]
Closed with b33fd78b2165d8242d564e21b99e92d66f6b2988
