### ISSUE TITLE
None unified look

### ISSUE THREAD

**Issue by Xiaoming94** [cthit/EatIT#17]
![2016-02-23-14 54 59-screenshot](https://cloud.githubusercontent.com/assets/6448975/13253714/afa69d30-da3d-11e5-8d73-4c14367be887.png)

The app doesn't have unified look across the browsers, For example on non-webkit Browsers (like Firefox), The app will load properties from the GTK-theme (On Linux Machines)

**Comment by Xiaoming94** [comment]
Oh btw, the strange screenshot is due to random screen tearing on x11 :P

**Comment by hjorthjort** [comment]
This turned out to be because of @Xiaoming94 s browser settings setting all input fields to black background as default. This can be an important aspect for accesibility to a site, and we should not force a certain color on the input fields.
