### ISSUE TITLE
Migrate to self hosting

### ISSUE THREAD

**Issue by hjorthjort** [cthit/EatIT#18]
Meteor is shutting down maintenance and hosting on meteor.com, and meteor.com has been unstable in the past. We should start our own meteor server to host EatIT.

**Comment by jesperlindstrom** [comment]
Got it up and running on Kamino. Websocket-support seems to be broken (might require additional configuration in Apache/Passenger?). Realtime updates seem to be working nonetheless.
```
WebSocket connection to 'ws://eatit.chalmers.it/sockjs/666/1l8g0lf2/websocket' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
```
