### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by Gorom** [cthit/EatIT#2]
The person creating the thing should be able to enter his or her phone number. People could then press a "pay" button next to their order which in opens Swish on their phone with phone number and ammount allready filled in.

**Comment by lindskogen** [comment]
This would be easy to integrate with swish's API, IF THERE WAS ONE!?

**Comment by Gorom** [comment]
THERE IS ONE!!!

**Comment by lindskogen** [comment]
You're right!

**Comment by Edholm** [comment]
[For reference (in swedish)](https://www.getswish.se/handel/)

**Comment by lindskogen** [comment]
This could be troublesome: As I understand it, the swish API only allows registered merchants to receive payments?

**Comment by MrLinker** [comment]
This is implemented and works on Android and from what I've heard works for iPhone as well. 

Then couldn't this issue be considered solved?

**Comment by lindskogen** [comment]
This is resolved as of a8f400d72bf57f533b61e6bc831521c26dbe35bd
