### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by SSundstrom** [cthit/EatIT#23]
It is quite common that people accidentally remove other people from the eatit list.
An Undo function would be helpful. <s>Or make it harder to remove people from the list.</s>

**Comment by MrLinker** [comment]
Pull request #27 adds en confirmation dialog when attempting to remove an order. Consider this done?

**Comment by hulthe** [comment]
Reopening this as I would like to see an undo-feature.

**Comment by Portals** [comment]
#49 Resolves this
